language: objective-c
osx_image: xcode7.3
xcode_workspace: SwiftyJSONAccelerator.xcworkspace
xcode_scheme: SwiftyJSONAccelerator
xcode_sdk: macosx10.11
podfile: Podfile
install:
  - bundle install
  - gem install cocoapods
  - ./install_swiftlint.sh
script:
  - make build
  - make ci_tests
  - swiftlint
after_success:
  - slather
  - bash <(curl -s https://codecov.io/bash) -f build/slather/cobertura.xml
